### ISSUE TITLE
Will you update this mod sometime to 1.13?

### ISSUE THREAD

**Issue by Xeonmeister** [maruohon/paintedbiomes#10]
Are you planning on updating it? Or can you (or anyone) suggest me a 1.13 compatible mod which also has the option to generate from a biome map png? The only world generation mods i find for 1.13 are just some custom biomes. Spigot plugins are also welcome, i'd just like to generate a 1.13 world from a custom biome map.

**Comment by maruohon** [comment]
The intention is to update all my mods to 1.13.2. I haven't looked at Forge 1.13.2 yet as it's still in Beta and I believe is changing around somewhat and also probably has a bunch of missing things. But I could take a look at it and see if it's even currently possible to update this mod with what Forge has to offer at the moment.

**Comment by Xeonmeister** [comment]
Oh thx for the quick answer. I just wanted to know if u plan on updating it and wanted to know if you are even active or not. Since i'm kinda new to this site i don't know how to check when people were last active. Anyways, sorry for opening an issue, since i know this function is not for asking questions, i just don't really know how else i could ve done it.

**Comment by maruohon** [comment]
CurseForge comments are one way, and I do also have my own Discord server, although it's only linked on a couple of my mod project pages on CurseForge. As for activity, if you go to https://github.com/maruohon you can see the "contribution activity" and the mods that I've been working on recently.
