### ISSUE TITLE
1.7.10 Not working, 0.5.0 

### ISSUE THREAD

**Issue by StarWarp** [maruohon/paintedbiomes#13]
I cant get the 1.7.10 edition of this mod to work

I have enabled the configuration for it to work in dim0
I have the template image in the proper folder

Enabling the Biome handling outside of the template image, makes the entire world that biome, which is the same result as if I just delete my template image completely and make a world.

My template image is saved as biomes.png, and contains only hex colors listed in the config.

Not sure what I'm doing wrong, any help would be appreciated :-)

**Comment by maruohon** [comment]
Well I can't really check or say anything unless you post your config file and template image for me to take a look at. I assume there must be a mistake somewhere, unless the mod is just completely broken (which shouldn't be the case, at least it must have worked in my simple testing setup without almost any other mods before I release a version).

If it seems to treat everything as "outside template area", then check your template location again, that there aren't typos or capital letters or spaces in any of the directory or file names etc. Also how large is your template image, and how did you align it in the world? Did you check at that location and not just around the world spawn, wherever that might be?

**Comment by StarWarp** [comment]
Thanks for such a quick response man!

my template image is 512x512 because im just trying to test the mod, In the configs its aligned to be centered at 0,0, and I checked there (not world spawn)

my directory is as follows: config\paintedbiomes\templates\dim0\biomes.png

my config file is pasted here: https://pastebin.com/i2cjT7HN

Im not running it with any other mods.

You're a hero for helping me out lmao, I have a sneaking suspicion that im just being really dumb about something.

**Comment by maruohon** [comment]
It has been a very long time since I've touched the mod at all, so I don't really remember much about how stuff works...

But you definitely seem to be missing some stuff in the config. At least you don't have the mod set to be enabled in any dimensions.

```
Generic {
    # Extra options for the ChunkProvider (only used for VANILLA_FLAT).
    S:chunkProviderOptions=
 
    # The ChunkProvider to use. Valid values: VANILLA_DEFAULT, VANILLA_FLAT, VANILLA_HELL, VANILLA_END
    S:chunkProviderType=
 
    # A list of dimensions where Painted Biomes should be enabled.
    I:enabledInDimensions <
     >
 
    # Set to true to use an overridden ChunkProvider. Select the type in chunkProviderType.
    B:overrideChunkProvider=false
```

So at least you need to add dimension 0 i.e. the value `0` to `enabledInDimensions`. Now sadly I don't remember at all if you are supposed to enable `overrideChunkProvider` and select `VANILLA_DEFAULT` in `chunkProviderType`, or in what case you would use those... Did the CurseForge page mention something about those? I guess first just enable it in dimension 0, if nothing happens, then try setting those two configs, or if that doesn't work either then alternatively try enabling the GenLayer config (but I believe that one is not recommended in most cases).

**Comment by maruohon** [comment]
Oh and I remember the Forge config parser at least at some point in the past being rather picky about the string list config format. So you need to indent the 0 value at least to the same starting level as the config name, or even further.

So try it like this:
```
    # A list of dimensions where Painted Biomes should be enabled.
    I:enabledInDimensions <
      0
     >
```

**Comment by StarWarp** [comment]
Ope! I regenerated the config files while debugging and must have forgotten to re-add the dimm number

It still doesnt work with the dim number added and correctly indented, ive tried every combination of overrideChunkProvider settings and GenLayer configs, interestingly enough if both genlayer is enabled, and overrideChunkProvider is set to VANILLA_DEFAULT, it generates a world with an infinitely big mesa biome for some reason

new paste: https://pastebin.com/YPcx2JBe

test image I've been trying to get work
![biomes png](https://github.com/maruohon/paintedbiomes/assets/30935424/fe48cba6-7543-4068-97aa-30bdc27a9aa5)

**Comment by maruohon** [comment]
It seems to be working in my test instance. I used your config and template image. I just changed the `overrideChunkProvider` value back to `false` for the first attempt, and that first attempt already worked.

![2023-07-09_13 07 09](https://github.com/maruohon/paintedbiomes/assets/2331050/d63bf605-1dcd-4d92-9bf4-5de5edc2a345)

Check your game console/log when you log into the world, do you see these two lines from Painted Biomes (empty lines added for clarity)?

```
[13:06:07] [Server thread/INFO] [FML]: Loading dimension 0 (PaintedBiomes_GH_13) (net.minecraft.server.integrated.IntegratedServer@2d531e98)
[13:06:07] [Server thread/INFO] [FML]: Loading dimension 1 (PaintedBiomes_GH_13) (net.minecraft.server.integrated.IntegratedServer@2d531e98)
[13:06:07] [Server thread/INFO] [FML]: Loading dimension -1 (PaintedBiomes_GH_13) (net.minecraft.server.integrated.IntegratedServer@2d531e98)

[13:06:07] [Server thread/INFO] [paintedbiomes]: Wrapping the WorldChunkManager (of type net.minecraft.world.biome.WorldChunkManager) of dimension 0 with fi.dy.masa.paintedbiomes.world.WorldChunkManagerPaintedBiomes
[13:06:07] [Server thread/INFO] [paintedbiomes]: Successfully read template image from '/home/masa/mc/PrismLauncher/instances/Forge 1.7.10/minecraft/config/paintedbiomes/templates/dim0/biomes.png'

[13:06:07] [Server thread/INFO]: Preparing start region for level 0
[13:06:08] [Server thread/INFO]: Changing view distance to 12, from 10
```

**Comment by StarWarp** [comment]
![image](https://github.com/maruohon/paintedbiomes/assets/30935424/f2c7b100-6dea-480e-8a6d-caac6dadf13c)
this is what I get when I generate a world with that exact config with **overrideChunkProvider**  set to **false**

in the singleplayer console log I dont get anything mentioning painted biomes, instead my generation messages look like this:

[14:28:41] [Server thread/INFO]: Loading dimension 0 (test) (net.minecraft.server.integrated.IntegratedServer@11dde0d0)
[14:28:41] [Server thread/INFO]: Loading dimension 1 (test) (net.minecraft.server.integrated.IntegratedServer@11dde0d0)
[14:28:41] [Server thread/INFO]: Loading dimension -1 (test) (net.minecraft.server.integrated.IntegratedServer@11dde0d0)
[14:28:41] [Server thread/INFO]: Preparing start region for level 0
[14:28:42] [Server thread/INFO]: Preparing spawn area: 34%
[14:28:43] [Server thread/INFO]: Preparing spawn area: 59%
[14:28:44] [Server thread/INFO]: Preparing spawn area: 90%

full paste excerpt: https://pastebin.com/CekEdqzR

**Comment by maruohon** [comment]
Look on lines 111 and 149. Line 111 is weird because it says it's wrapping the nether chunk manager in dimension 0... what? Was that some weird test dimension?

But there is no line about loading the template image. That would indicate that either the image is not found, or there is some permission issue otherwise and it's not being read. The path you posted earlier was correct, but did you just type that out to the message or copy paste it? Check that there isn't some stupid typo somewhere.

![image](https://github.com/maruohon/paintedbiomes/assets/2331050/b504be60-bc94-47fc-bd6a-69148d91eea6)

**Comment by StarWarp** [comment]
no weird dimension nonsense, this is the only mod and im trying to generate a world with default generation settings.

I copypasted the directory path directly earlier, and I've double checked it a few thousand times, so I dont think its that.

**Comment by StarWarp** [comment]
played around with my java installation, ended up deleting my JDK installation as a hail mary, and it ended up switching the log from wrapping the hell chunk manager (why it was doing that I have no clue), to just:

[Server thread/WARN]: Unable to find spawn biome

which is slightly more helpful
still no dice on any change in the actual world though

**Comment by StarWarp** [comment]
did some more testing, there seems to be some discrepancies between operating systems, maybe in the format for how the path for the image file? 

I got it to work when I used a linux device, because I saw your file manager was Linux and tried to replicate your environment for testing

Ran the same setup from a USB on some differing devices

Main PC - Windows 10 - FAIL - does not detect template folder
Aux PC - Windows 11 - FAIL - crashes on startup, crashes keep mentioning invalid cache
Laptop - Ubuntu - **Generates successfully** 

Thanks a lot for the quick replies, you've been a lot of help

**Comment by StarWarp** [comment]
did some more testing, there seems to be some discrepancies between operating systems, maybe in the format for the path for the image file?

I got it to work when I used a linux device, because I saw your file manager was Linux and tried to replicate your environment for testing

Ran the same setup from a USB on some differing devices

Main PC - Windows 10 - FAIL - does not detect template folder
Aux PC - Windows 11 - FAIL - crashes on startup, crashes keep mentioning invalid cache
Laptop - Ubuntu - Generates successfully

Thanks a lot for the quick replies, you've been a lot of help

**Comment by maruohon** [comment]
Okay that is weird. Unfortunately I don't have a Windows PC to test on currently. But these old versions should have been tested on Windows at the time, because I used to do modding on Windows until... was it mid 2021 when I changed my modding PC to also run on Linux (and actually stopped using 2 separate PCs). And looking at the code it doesn't seem like it's using slash syntax for file paths anywhere or anything like that.

**Comment by StarWarp** [comment]
did more testing, turns out it was actually an error on photoshops part, when I used linux, I used the native GIMP to make the test image, and when I was on windows, I used a photoshop test image.

did some digging and it turns out that the reason it wasnt loading the template was because photoshop was saving it as an "ehnanced .png" which in all ways looked to me like a .png in the filepath, but actually was encoded differently.

Solution: export as a default png in photoshop and it works on windows

mystery solved
