### ISSUE TITLE
Some default colours conflict with biome IDs available to mods

### ISSUE THREAD

**Issue by JakobOvrum** [maruohon/paintedbiomes#2]
I dumped the unused biome IDs in vanilla and compared to the default colour mapping in paintedbiomes.cfg with a script:
```
Color for biome "Deep Ocean" [000030] conflicts with unused biome ID 48
Color for biome Ocean [000070] conflicts with unused biome ID 112
Color for biome River [0000FF] conflicts with unused biome ID 255
```
Thus, if a mod biome is assigned any of these IDs, their automatically generated colour mappings can override the default mappings.

I think this was the conflict issue I was having in the first place. A workaround is of course simply not to assign any biomes to those IDs.

**Comment by maruohon** [comment]
Hmm, right. Well that comes from the fact that I decided to use the blue channel for the default color. Didn't even think of this conflict :p
Maybe I should change the default mapping from BiomeID to the red or green channel?  Or should I generate random colors for new biomes (just check that they are unused)? Not sure which would make most sense for default values.
